name: Quarkus packaging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: "ghcr.io"

jobs:
  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Start Postgres DB
        run: |
          ./postgres-download-scripts-16.3.sh
          ./postgres-create-db.sh
          ./postgres-start.sh
        working-directory: backend

      - name: Build
        run: cd backend && ./mvnw package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: convert github repository name to lowercase
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: convert github registry name to lowercase
        run: echo "IMAGE_REGISTRY=$(echo ${{ env.REGISTRY }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Build and push server image
#        uses: docker/build-push-action@v3
#        with:
#          context: ./backend
#          file: ./backend/src/main/docker/Dockerfile.jvm
#          push: true
#          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}-backend:latest
#          cache-from: type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}-backend:buildcache
#          cache-to: type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}-backend:buildcache,mode=max